<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmAgreement
 *
 * Structure class for relation public.xm_agreement.
 * (DC2Type:array)
 *
 * fields:
 * (DC2Type:array)
 *
 * @see RowStructure
 */
class XmAgreement extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_agreement')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('owner_id', 'int4')
            ->addField('text', 'text')
            ->addField('status', 'text')
            ->addField('fields', 'text')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ->addField('locked', 'bool')
            ->addField('percent', 'int4')
            ->addField('percent_text', 'varchar')
            ;
    }
}
