<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmFacebookPages
 *
 * Structure class for relation public.xm_facebook_pages.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class XmFacebookPages extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_facebook_pages')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('user_id', 'int4')
            ->addField('name', 'varchar')
            ->addField('page_id', 'varchar')
            ->addField('category', 'varchar')
            ->addField('url', 'varchar')
            ->addField('app_created', 'bool')
            ;
    }
}
