<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmInvoice
 *
 * Structure class for relation public.xm_invoice.
 * (DC2Type:array)
 *
 * payment_options:
 * (DC2Type:array)
 *
 * @see RowStructure
 */
class XmInvoice extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_invoice')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('order_id', 'int4')
            ->addField('state', 'varchar')
            ->addField('statemessage', 'text')
            ->addField('payment', 'varchar')
            ->addField('description', 'varchar')
            ->addField('foreign_id', 'varchar')
            ->addField('payment_options', 'text')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ->addField('error', 'varchar')
            ;
    }
}
