<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmLicense
 *
 * Structure class for relation public.xm_license.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class XmLicense extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_license')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('title', 'text')
            ->addField('sort_order', 'int4')
            ->addField('code', 'varchar')
            ->addField('by_default', 'bool')
            ->addField('text_source', 'text')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ;
    }
}
