<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmLicenseOption
 *
 * Structure class for relation public.xm_license_option.
 * (DC2Type:json_array)
 *
 * values2:
 * (DC2Type:json_array)
 *
 * @see RowStructure
 */
class XmLicenseOption extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_license_option')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('license_id', 'int4')
            ->addField('name', 'text')
            ->addField('title', 'text')
            ->addField('values2', 'text')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ;
    }
}
