<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmMetadataKey
 *
 * Structure class for relation public.xm_metadata_key.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class XmMetadataKey extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_metadata_key')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('alias_id', 'int4')
            ->addField('title', 'varchar')
            ->addField('sort_order', 'int4')
            ->addField('code', 'varchar')
            ->addField('uniq', 'bool')
            ->addField('multiple', 'bool')
            ->addField('required', 'bool')
            ->addField('featured', 'bool')
            ->addField('editable', 'bool')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ->addField('sort_order_in_search', 'int4')
            ;
    }
}
