<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmOpportunity
 *
 * Structure class for relation public.xm_opportunity.
 * (DC2Type:array)
 *
 * links:
 * (DC2Type:array)
 *
 * @see RowStructure
 */
class XmOpportunity extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_opportunity')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('owner_id', 'int4')
            ->addField('description', 'text')
            ->addField('license_type', 'varchar')
            ->addField('project_description', 'text')
            ->addField('budget', 'float8')
            ->addField('status', 'varchar')
            ->addField('links', 'text')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ;
    }
}
