<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmOpportunityStore
 *
 * Structure class for relation public.xm_opportunity_store.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class XmOpportunityStore extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_opportunity_store')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('track_id', 'int4')
            ->addField('opportunity_id', 'int4')
            ->addField('amount', 'float8')
            ->addField('description', 'text')
            ;
    }
}
