<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmOrder
 *
 * Structure class for relation public.xm_order.
 * (DC2Type:json_array)
 *
 * license_options_values:
 * (DC2Type:json_array)
 * license_params:
 * (DC2Type:array)
 * fields:
 * (DC2Type:json_array)
 *
 * @see RowStructure
 */
class XmOrder extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_order')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('track_id', 'int4')
            ->addField('license_id', 'int4')
            ->addField('user_id', 'int4')
            ->addField('state', 'varchar')
            ->addField('amount', 'float8')
            ->addField('license_options_values', 'text')
            ->addField('license_params', 'text')
            ->addField('license_text_source', 'text')
            ->addField('fields', 'text')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ->addField('deleted_at', 'timestamp')
            ->addField('deleted', 'bool')
            ->addField('price_type', 'varchar')
            ->addField('sign_license_date', 'timestamp')
            ->addField('amount_seller', 'float8')
            ->addField('amount_tomatoshark', 'float8')
            ->addField('invoice_id', 'int4')
            ;
    }
}
