<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmPayout
 *
 * Structure class for relation public.xm_payout.
 * (DC2Type:json_array)
 *
 * requisites:
 * (DC2Type:json_array)
 *
 * @see RowStructure
 */
class XmPayout extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_payout')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('user_id', 'int4')
            ->addField('requisites', 'text')
            ->addField('name', 'varchar')
            ->addField('default_val', 'bool')
            ->addField('confirmed', 'bool')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ;
    }
}
