<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmProfileContent
 *
 * Structure class for relation public.xm_profile_content.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class XmProfileContent extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_profile_content')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('profile_app_id', 'int4')
            ->addField('profile_source_id', 'int4')
            ->addField('profile_category_id', 'int4')
            ->addField('status', 'varchar')
            ->addField('link', 'varchar')
            ->addField('image_path', 'varchar')
            ->addField('description', 'varchar')
            ->addField('content', 'varchar')
            ->addField('headline', 'varchar')
            ->addField('publication_date', 'timestamp')
            ->addField('sort', 'int4')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ;
    }
}
