<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmRequestLog
 *
 * Structure class for relation public.xm_request_log.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class XmRequestLog extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_request_log')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('cdate', 'timestamp')
            ->addField('token', 'varchar')
            ->addField('route', 'varchar')
            ->addField('method', 'varchar')
            ->addField('request_content', 'varchar')
            ->addField('event', 'varchar')
            ->addField('event_data', 'text')
            ->addField('user_id', 'int4')
            ->addField('utm_campaign', 'varchar')
            ->addField('utm_source', 'varchar')
            ->addField('utm_term', 'varchar')
            ->addField('utm_content', 'varchar')
            ->addField('app_id', 'varchar')
            ;
    }
}
