<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmTransaction
 *
 * Structure class for relation public.xm_transaction.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class XmTransaction extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_transaction')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('owner_id', 'int4')
            ->addField('amount', 'float8')
            ->addField('payout_type', 'varchar')
            ->addField('status', 'int2')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ;
    }
}
