<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmTrackSample
 *
 * Structure class for relation public.xm_track_sample.
 * (DC2Type:array)
 *
 * waveform:
 * (DC2Type:array)
 *
 * @see RowStructure
 */
class XmTrackSample extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_track_sample')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('track_id', 'int4')
            ->addField('owner_id', 'int4')
            ->addField('type', 'varchar')
            ->addField('duration', 'int4')
            ->addField('waveform_url', 'varchar')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ->addField('storage_key', 'varchar')
            ->addField('storage', 'varchar')
            ->addField('mime_type', 'varchar')
            ->addField('waveform', 'text')
            ;
    }
}
