<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmUpload
 *
 * Structure class for relation public.xm_upload.
 * (DC2Type:array)
 *
 * metadata:
 * (DC2Type:array)
 *
 * @see RowStructure
 */
class XmUpload extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_upload')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('owner_id', 'int4')
            ->addField('uploader_id', 'int4')
            ->addField('storage_key', 'varchar')
            ->addField('storage', 'varchar')
            ->addField('mime_type', 'varchar')
            ->addField('original_filename', 'varchar')
            ->addField('source', 'varchar')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ->addField('metadata', 'text')
            ->addField('token', 'varchar')
            ->addField('status', 'int4')
            ;
    }
}
