<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmUserProfile
 *
 * Structure class for relation public.xm_user_profile.
 * (DC2Type:json_array)
 *
 * data:
 * (DC2Type:json_array)
 *
 * @see RowStructure
 */
class XmUserProfile extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_user_profile')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('cover_id', 'int4')
            ->addField('cover_company_id', 'int4')
            ->addField('data', 'text')
            ->addField('phone', 'varchar')
            ->addField('website', 'varchar')
            ->addField('company_brand_title', 'varchar')
            ->addField('company_legal_name', 'varchar')
            ->addField('company_website', 'varchar')
            ->addField('company_summary', 'varchar')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ->addField('price_type', 'varchar')
            ;
    }
}
