<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmUser
 *
 * Structure class for relation public.xm_user.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class XmUser extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_user')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('profile_id', 'int4')
            ->addField('application_id', 'int4')
            ->addField('email', 'varchar')
            ->addField('password', 'varchar')
            ->addField('fname', 'varchar')
            ->addField('lname', 'varchar')
            ->addField('status', 'int2')
            ->addField('role', 'varchar')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ->addField('lang', 'varchar')
            ->addField('uuid', 'varchar')
            ->addField('common', 'bool')
            ->addField('terms_accepted', 'bool')
            ->addField('resend_date', 'timestamp')
            ->addField('utm_campaign', 'varchar')
            ;
    }
}
