<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * XmVOrders
 *
 * Structure class for relation public.xm_v_orders.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class XmVOrders extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.xm_v_orders')
            ->setPrimaryKey([])
            ->addField('id', 'int4')
            ->addField('order_state', 'varchar')
            ->addField('amount', 'float8')
            ->addField('price_type', 'varchar')
            ->addField('cdate', 'timestamp')
            ->addField('mdate', 'timestamp')
            ->addField('track_filename', 'varchar')
            ->addField('user_email', 'varchar')
            ->addField('user_fname', 'varchar')
            ->addField('user_lname', 'varchar')
            ->addField('invoice_id', 'int4')
            ->addField('invoice_state', 'varchar')
            ->addField('invoice_statemessage', 'text')
            ->addField('invoice_payment', 'varchar')
            ->addField('invoice_description', 'varchar')
            ->addField('invoice_foreign_id', 'varchar')
            ->addField('invoice_payment_options', 'text')
            ->addField('invoice_cdate', 'timestamp')
            ->addField('invoice_mdate', 'timestamp')
            ->addField('owner_email', 'varchar')
            ->addField('owner_fname', 'varchar')
            ->addField('owner_lname', 'varchar')
            ->addField('track_id', 'int4')
            ->addField('license_id', 'int4')
            ->addField('user_id', 'int4')
            ->addField('owner_id', 'int4')
            ;
    }
}
